### ISSUE TITLE
[Optimize] update configuration for Eureka

### ISSUE THREAD

**Issue by guoshupei** [apache/incubator-linkis#3775]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar feature requirement.

### Problem Description

Add the following configuration to the application-eureka.yml

```
server:
  enable-self-preservation: false
  eviction-interval-timer-in-ms: 10000
  response-cache-update-interval-ms: 3000
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
